# Generated by Django 4.2.17 on 2025-10-22 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_group', models.CharField(max_length=100)),
                ('skill_subgroup', models.CharField(max_length=100)),
                ('skill_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('user', 'skill_group', 'skill_subgroup', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='ApprovedCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_group', models.CharField(max_length=100)),
                ('skill_subgroup', models.CharField(max_length=100)),
                ('skill_name', models.CharField(max_length=100)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_enrollment', to='firstapp.courseenrollmentrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'skill_group', 'skill_subgroup', 'skill_name')},
            },
        ),
    ]
