# Generated by Django 4.2.17 on 2025-07-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_altuser_profile_picture_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altuser',
            name='profile_picture',
        ),
    ]
