# Generated by Django 4.2.17 on 2025-10-30 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_courseenrollmentrequest_approvedcourseenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_group', models.CharField(max_length=100)),
                ('skill_subgroup', models.CharField(max_length=100)),
                ('skill_name', models.CharField(max_length=100)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('max_students', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_students', models.ManyToManyField(related_name='enrolled_courses', through='firstapp.CourseAttendance', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
                'unique_together': {('skill_group', 'skill_subgroup', 'skill_name', 'scheduled_date', 'scheduled_time')},
            },
        ),
        migrations.AddField(
            model_name='courseattendance',
            name='scheduled_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.scheduledcourse'),
        ),
        migrations.AddField(
            model_name='courseattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='courseattendance',
            unique_together={('student', 'scheduled_course')},
        ),
    ]
