# Generated by Django 4.2.17 on 2025-07-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_altuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='altuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='altuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='altuser',
            name='sur_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='sur_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
