# Generated by Django 4.2.17 on 2025-11-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_courseattendance_scheduledcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedcourseenrollment',
            name='skill_group',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='approvedcourseenrollment',
            name='skill_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='approvedcourseenrollment',
            name='skill_subgroup',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='courseenrollmentrequest',
            name='skill_group',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='courseenrollmentrequest',
            name='skill_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='courseenrollmentrequest',
            name='skill_subgroup',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduledcourse',
            name='skill_group',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduledcourse',
            name='skill_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduledcourse',
            name='skill_subgroup',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skillgroup',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skillname',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skillsubgroup',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
