# Generated by Django 4.2.17 on 2025-07-16 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import firstapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_remove_altuser_age_remove_altuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=firstapp.models.user_profile_picture_path),
        ),
        migrations.CreateModel(
            name='SkillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_level', models.PositiveIntegerField(blank=True, null=True)),
                ('new_level', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_histories', to='firstapp.profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='firstapp.skill')),
            ],
        ),
    ]
